// GENERAL TYPES
export const FETCH_REQUESTED = 'FETCH_REQUESTED'
export const FETCH_START = 'FETCH_START'
export const FETCH_SUCCEEDED = 'FETCH_SUCCEEDED'
export const FETCH_FAILED = 'FETCH_FAILED'

export const UPDATE_REQUESTED = 'UPDATE_REQUESTED'
export const UPDATE_START = 'UPDATE_START'
export const UPDATE_SUCCEEDED = 'UPDATE_SUCCEEDED'
export const UPDATE_FAILED = 'UPDATE_FAILED'

// REDUCERS
export const TODOS_DELETE = 'TODOS_DELETE'
export const TODOS_ADD = 'TODOS_ADD'
export const TODOS_TOGGLE = 'TODOS_TOGGLE'
export const TODOS = 'TODOS'
